spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      zalando:
        logbook: trace
  file:
    name: logging.log

logbook:
  minimum-status: 400
  strategy: body-only-if-status-at-least
